### ISSUE TITLE
Typescript issues with redux-toolkit@2.0.0-beta.0

### ISSUE THREAD

**Issue by guillaumebrunerie** [reduxjs/react-redux#2059]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- Redux: 5.0.0-beta.0
- Redux Toolkit: 2.0.0-beta.0
- React Redux: 8.1.2

### What is the current behavior?

I updated to the beta version of Redux Toolkit (`npm i @reduxjs/toolkit@2.0.0-beta.0 redux@5.0.0-beta.0`), but when I typecheck my project I get a bunch of errors in react-redux (see below). Is that expected? Is there a beta version of react-redux I should install?
```
[...]
node_modules/react-redux/es/connect/selectorFactory.d.ts:26:25 - error TS2344: Type 'Action<unknown>' does not satisfy the constraint 'Action<string>'.

26     (dispatch: Dispatch<Action<unknown>>, ownProps: TOwnProps): TDispatchProps;
                           ~~~~~~~~~~~~~~~

node_modules/react-redux/es/connect/selectorFactory.d.ts:26:32 - error TS2344: Type 'unknown' does not satisfy the constraint 'string'.

26     (dispatch: Dispatch<Action<unknown>>, ownProps: TOwnProps): TDispatchProps;
                                  ~~~~~~~

node_modules/react-redux/es/connect/selectorFactory.d.ts:37:55 - error TS2344: Type 'Action<unknown>' does not satisfy the constraint 'Action<string>'.

37     readonly initMapStateToProps: (dispatch: Dispatch<Action<unknown>>, options: InitOptions<TStateProps, TOwnProps, TMergedProps, State>) => WrappedMapStateToProps<TStateProps, TOwnProps, State>;
                                                         ~~~~~~~~~~~~~~~

node_modules/react-redux/es/connect/selectorFactory.d.ts:37:62 - error TS2344: Type 'unknown' does not satisfy the constraint 'string'.

37     readonly initMapStateToProps: (dispatch: Dispatch<Action<unknown>>, options: InitOptions<TStateProps, TOwnProps, TMergedProps, State>) => WrappedMapStateToProps<TStateProps, TOwnProps, State>;
                                                                ~~~~~~~

node_modules/react-redux/es/connect/selectorFactory.d.ts:38:58 - error TS2344: Type 'Action<unknown>' does not satisfy the constraint 'Action<string>'.

38     readonly initMapDispatchToProps: (dispatch: Dispatch<Action<unknown>>, options: InitOptions<TStateProps, TOwnProps, TMergedProps, State>) => WrappedMapDispatchToProps<TDispatchProps, TOwnProps>;
                                                            ~~~~~~~~~~~~~~~
[...]
```

### What is the expected behavior?

No errors

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
I had been working on a `9.0.0-alpha` release that makes use of the updated TS types, and got bogged down in trying to work on things.  Haven't had time to get back to it, and I'm mostly taking off the month of August at this point to recover from being overloaded.

**Comment by markerikson** [comment]
Going to close this under the assumption that 9.0.0-alpha.0 fixes those types issues. Please let me know if it doesn't!
