### ISSUE TITLE
react-redux@5.1.0 node@6.x.x TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by VSuryaBhargava** [reduxjs/react-redux#1072]
I am getting **Uncaught TypeError: Object(...) is not a function** in the browser because connect is not being imported properly ( its value is undefined )

```js
import { connect } from "react-redux";
import { action1, action2 } from "client/store/actions";
import Component from "Components/Component";

const mapDispatchToProps = { action1, action2 };
const mapStateToProps = state => ({
    data: state.data
});

export default connect(mapStateToProps, mapDispatchToProps)(Component);
// ------------^ Uncaught TypeError: Object(...) is not a function
```

* react-redux version: 5.1.0 ( works fine with 5.0.7 )
* node verison: 6.2.2
* npm version: 3.9.5

Maybe this is the culprit?
```js
module.exports = {
  presets: [['@babel/env', { loose, modules: false }]],
  plugins: [
    ['@babel/proposal-decorators', { legacy: true }],
    ['@babel/proposal-object-rest-spread', { loose }],
    '@babel/transform-react-jsx',
    cjs && ['@babel/transform-modules-commonjs', { loose }],
// ---------------------------------^?
    ['@babel/transform-runtime', { useESModules: !cjs }],
  ].filter(Boolean),
}
```

These are the commits since 5.0.7: https://github.com/reduxjs/react-redux/compare/v5.1.0-test.1...master

**Comment by timdorr** [comment]
It looks like your build tool isn't importing react-redux correct. Unfortunately, this isn't a bug with the library. I would see about updating your tooling and ensuring it's generating the right output.
